const indianGirlsDressCategories = [
  {
    category: "Ethnic Dresses",
    subcategories: [
      "Anarkali Dresses",
      "Kurta Dresses",
      "Lehenga Dresses",
      "Indo-Western Dresses",
    ],
  },
  {
    category: "Casual and Everyday Dresses",
    subcategories: [
      "Cotton A-Line Dresses",
      "Tunic Dresses",
      "Floral Maxi Dresses",
      "Kaftan Dresses",
    ],
  },
  {
    category: "Party and Festive Dresses",
    subcategories: [
      "Sequined Dresses",
      "Cape Dresses",
      "Gown-Style Dresses",
      "Shimmer Dresses",
    ],
  },
  {
    category: "Fusion Wear",
    subcategories: [
      "Saree-Inspired Dresses",
      "Dhoti-Style Dresses",
      "Peplum Tops with Skirts",
    ],
  },
  {
    category: "Western Wear Dresses",
    subcategories: [
      "Skater Dresses",
      "Bodycon Dresses",
      "Off-Shoulder Dresses",
      "Shirt Dresses",
    ],
  },
  {
    category: "Seasonal and Vacation Dresses",
    subcategories: [
      "Summer Sundresses",
      "Winter Sweater Dresses",
      "Beachwear Dresses",
    ],
  },
  {
    category: "Bridal Dresses",
    subcategories: [
      "Engagement Gowns",
      "Reception Dresses",
      "Haldi/Mehendi Outfits",
    ],
  },
  // {
  //   category: "Kids and Teen Dresses",
  //   subcategories: [
  //     "Frilly Frocks",
  //     "Ethnic Kurtis",
  //     "Printed Dresses"
  //   ]
  // },
  {
    category: "Designer or Boutique Dresses",
    subcategories: ["Handcrafted Dresses", "Designer Lehengas", "Custom Gowns"],
  },
  {
    category: "Budget-Friendly Options",
    subcategories: [
      "Affordable Maxi Dresses",
      "Festive Ready Ethnic Wear",
      "Combo Offers",
    ],
  },
];

export const category = indianGirlsDressCategories.flatMap(
  (category) => category.subcategories
);

export const tweetTemplates = [
  "This dress is a dream come true! ✨👗 Shop now!",
  "Love at first sight? 💖👗 Grab it before it’s gone!",
  "Simple, stylish, stunning. 💃✨ Tap to shop!",
  "A perfect addition to your wardrobe! 👗🛍️ Click here!",
  "This dress is what style goals are made of! 🌟✨",
  "Add a touch of elegance to your look! 👗💫 Shop now!",
  "Ready for a wardrobe refresh? 💃✨ Tap here!",
  "Classic, comfortable, and chic! 👗🛍️ Get it here!",
  "This dress is calling your name! ✨💖 Click here!",
  "The perfect pick for any day! 🌸👗 Shop now!",
  "Who says you can’t have it all? 💃👗 Grab this beauty!",
  "Twirl into happiness with this dress! ✨🌸 Shop here!",
  "Get ready to turn heads! 💖👗 Tap to shop!",
  "Your next favorite outfit is just a click away! 🛍️💃",
  "Style made simple with this stunning dress! ✨👗",
  "What’s better than comfort + style? 🌟💃 Get yours now!",
  "This dress is an instant mood booster! 💖✨ Shop here!",
  "Start your day in style with this chic outfit! 👗🌸",
  "You’ll want to wear this everywhere! ✨👗 Click here!",
  "This dress is love at first sight! 💕🌟 Tap to shop!",
  "Effortlessly chic! 👗✨ Shop now!",
  "This dress = instant glam. 💃💖",
  "Because you deserve it. 🌸👗",
  "Stay stylish, stay stunning! ✨💃",
  "A must-have for your collection! 👗🛍️",
  "One dress, endless possibilities. 🌟✨",
  "Chic, simple, and stunning! 👗💫 Tap here!",
  "It’s your time to shine! 💖🌸",
  "Effortlessly elevate your style. ✨👗",
  "Style made simple. 💃💖",
  "Say yes to style with this beauty! 💕👗 Shop now!",
  "Dresses that make you feel amazing! ✨🌸",
  "Get ready to fall in love with your wardrobe! 💃💖",
  "Chic, stylish, and made for you! 👗✨",
  "This dress is a total mood! 🌟💃",
  "Feel confident, look stunning! 💖👗",
  "Because every day deserves great style! 🌸✨",
  "The easiest way to upgrade your wardrobe! 💃💫",
  "Comfort and style? Yes, please! 👗💖",
  "Find your new favorite dress today! ✨🌸",
  "Don’t miss out on this beauty! 👗✨ Shop now!",
  "Grab it before it’s gone! 💃🌟 Click here!",
  "Limited stock! 💖👗 Tap to shop!",
  "Your next go-to dress is just a click away! ✨🌸",
  "Why wait? Style it your way today! 💃👗",
  "Ready for a wardrobe upgrade? 🌟💖",
  "This dress won’t stay in stock for long! 👗✨ Shop here!",
  "Add it to your cart now! 💃🛍️",
  "Style like this doesn’t come every day! 🌸👗",
  "Your perfect outfit is waiting! 💖✨ Tap here!",
  "Feel confident, feel stylish! 👗✨",
  "This dress = ultimate vibes! 💃🌸",
  "Timeless, elegant, and yours to own! 👗💫",
  "Every closet needs this stunner! 💖👗",
  "Your outfit upgrade starts here! ✨💃",
  "Style, comfort, and everything in between! 🌟👗",
  "Own the moment in this beautiful dress! 💕💃",
  "Let your outfit speak for you! 👗🌸",
  "A dress that suits every occasion! 💖✨",
  "Transform your look effortlessly! 👗🌟",
  "A little bit of glam for your day! 💃💫",
  "Your search for the perfect dress ends here! 👗✨",
  "Feel beautiful in every step you take! 🌸💖",
  "Ready to turn everyday into a runway? 💃👗",
  "For those who love effortless elegance! ✨🌟",
  "This dress will leave you glowing! 👗💖",
  "A dress made to impress! 💃🌸",
  "Chic, classy, and totally you! 👗💫",
  "Add sparkle to your day with this gem! 💖✨",
  "Dress up, stand out, shine on! 💃🌟",
  "Fashion that feels good! 👗💖",
  "Your daily dose of style is here! 🌸💃",
  "Be bold, be beautiful! ✨👗",
  "One dress, infinite compliments! 💖🌟",
  "Step out in style today! 💃💫",
  "Celebrate your beauty with this dress! 👗✨",
  "Fashion that fits like a dream! 🌸💖",
  "Turn every moment into a memory! 💃👗",
  "Perfect for every mood, every moment! 🌟👗",
  "Style starts here! 💖💃",
  "Comfort you’ll love, style you’ll adore! ✨👗",
  "Made to make you smile! 💕🌸",
  "A little glam goes a long way! 👗🌟",
  "Step into sophistication! 💖💃",
  "Feel confident, feel radiant! ✨👗",
  "Look good, feel great! 💃💫",
  "This dress is pure perfection! 👗🌸",
  "Dress to impress, every single time! 💖✨",
  "Flawless style starts here! 🌟💃",
  "Say hello to effortless beauty! 👗💫",
  "A dress that’s as unique as you! 🌸💖",
  "Upgrade your wardrobe instantly! 👗✨",
  "Discover your new favorite! 💃🌟",
  "Because you’re worth it! 💖👗",
  "Feel pretty, look stunning! 🌸✨",
  "Own your look with this gorgeous dress! 👗💫",
  "Every detail is perfect! 💖🌟",
  "Flaunt your style effortlessly! 👗💃",
  "Your perfect fit is right here! 🌸💖",
  "Step into something amazing today! 👗✨",
  "The dress of your dreams awaits! 💃🌟",
  "Look fabulous, feel unstoppable! 👗💫",
  "Take on the day with confidence! 💖👗",
  "Classic style with a modern twist! 🌸✨",
  "Your closet is calling for this! 👗🌟",
  "Be your stylish self every day! 💃💫",
  "This dress is your new obsession! 👗✨",
  "Add elegance to your everyday! 🌸💖",
  "Step out in style and shine bright! 💃🌟",
  "Flawless fashion, just for you! 👗💫",
  "Make today a stylish one! 🌸👗",
  "Confidence is the best accessory! 💃✨",
  "A dress as beautiful as your smile! 💖🌟",
  "Own the moment, own the style! 👗💫",
  "Get ready to dazzle in this dress! 🌸✨",
  "Celebrate your unique style today! 💃💖",
  "This dress is made for YOU! 🌟👗",
  "Feel unstoppable in this outfit! 💃💫",
  "Fashion-forward and oh-so-comfortable! 🌸👗",
  "Add some magic to your wardrobe! 💖✨",
  "The easiest way to look amazing! 💃🌟",
  "Be your best-dressed self every day! 👗💫",
  "Turn heads everywhere you go! 💃🌸",
  "A dress that makes life beautiful! 🌟💖",
  "Style like this doesn’t come every day! 👗✨",
  "Every detail speaks elegance! 💃💫",
  "Feel the joy of dressing up! 🌸👗",
  "Step up your fashion game today! 💖✨",
  "Made with love, just for you! 💃🌟",
  "Because you deserve something special! 👗💫",
  "Your go-to outfit for every occasion! 🌸💖",
  "The perfect balance of comfort and style! 💃✨",
  "This dress makes every day a special one! 🌟👗",
  "Elegance that never fades! 💖💃",
  "The dress your wardrobe has been waiting for! 🌸✨",
  "Because great fashion should feel effortless! 💃🌟",
  "Confidence starts with the perfect outfit! 👗💫",
  "Wear your style, own your vibe! 💖🌸",
  "Step into style that fits your vibe! 🌟💃",
];
